model:
  name: Rainformer
  in_channels: 9
  hidden_dim: 96
  downscaling_factors: (4, 2, 2, 2)
  layers: (2, 2, 2, 2)
  heads: (3, 6, 12, 24)
  head_dim: 32
  window_size: 9
  relative_pos_embedding: True
data:
  name: "KNMI"
  root_dir: "./data/"
  batch_size: 16
optimizer:
  name: "adam"
  lr: 0.0001
summary:
  csi_thresholds: 0.3
  save_checkpoint_steps: 1
  keep_checkpoint_max: 5
train:
  name: "fp"
  epochs: 200
